language: node_js

node_js:
  - stable

branches:
  only:
    - develop

install:
  - npm install

script:
  - grunt build-web-app --no-sign
  - grunt build-desktop --no-sign

deploy:
  provider: releases
  api_key:
    secure: O5Ia18F6pn4zUs7ua+gxN/7j9FguplMFi6S2aAKr/StyV/f9Qxj8v84et9ockB3mQAzP4ka2Upu53bvXZsaxelnFVlWRaIBWTPCATj1kmU5Bh2TaUtRck82Ql4bvl/0pXEmyDVergoEVEu4z3dn3mk1bGnqmpBbzXQtrVU4UEktmSGdfgbmK7TNsyfFoeEejWJq5XKlZQtsG0MBBZc3X9JKNWjXsyphdGOjxR7iVndeTJtda0d1jrrqLWZ5Oj3oPbRfkW2eAbj94YUvXUn6pB4B2Psi7o8xZJb4HO/VjMHqSoWIaphiPUdWVjtKO/ciI7v6rVTcBxphM0kxPatlX1L8VUvlWnvDCXrmzcDX7sIMj78sW9NHQWBRqBDXKk4z9mz5DbgPzerRN+Xu/Wmtz1QQCaUH4m8yGoDGt4xodGex7GsarLXUocz8/5C7TDmuvwGQr/9wYl4qYzd9b/qOhJ6Vzuf3G3EMpd1cqbg/hyYkxC+HVq0ZD1DAWaCUbltEHeVg5nCIng7YoZm0ZoQhb1LMR4dcIKgglmoprPx3zYX+uguBqU/1EU0vMfcGpOpQTTn2o6zhSerXBXRLsHnxl28KOYmcZlD94cECtrrB2hNO6/LbslhcgSTfq24oL3Vna+u2cvb9d1DE8RtJnsnCXfCu8RcmtqQfGh2vzWx0ZN/4=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: dist/desktop/KeeWeb-*.deb
  on:
    repo: cyosp/keeweb
    branch: develop
