name: Build and publish
on:
  push:
    tags:
      - '*'
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tag
        run: echo "NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Upgrade Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm modules
        run: npm install

      - name: Build application
        run: grunt

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: keeweb-dist-folder
          path: dist

  publish-on-docker:
    runs-on: ubuntu-latest
    needs:
      - build-app
    steps:
      - name: Get tag name
        id: tag
        run: echo "NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: keeweb-dist-folder
          path: dist

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v6.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: package/docker/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: cyosp/${{ github.event.repository.name }}:${{ steps.tag.outputs.NAME }}

  package-app:
    runs-on: macos-latest
    needs:
      - build-app
    steps:
      - name: Get tag name
        id: tag
        run: echo "NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: keeweb-dist-folder
          path: dist

      - name: Upgrade Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm modules
        run: npm install

      - name: Install grunt
        run: sudo npm i -g grunt-cli

      - name: Build MacOS packages
        run: grunt --max-old-space-size=4096 desktop-darwin --skip-sign

      - name: Install prerequisites to package
        run: brew install fileicon create-dmg

      - name: Create x64 app installer
        run: ./macos-app/package x64

      - name: Rename x64 DMG file
        run: mv KeeWeb.dmg KeeWeb-${{ steps.tag.outputs.NAME }}.x64.dmg

      - name: Create arm64 app installer
        run: ./macos-app/package arm64

      - name: Rename arm64 DMG file
        run: mv KeeWeb.dmg KeeWeb-${{ steps.tag.outputs.NAME }}.arm64.dmg

      - name: Install coreutils for sha512sum
        run: brew install coreutils

      - name: Create check sum file
        run: sha512sum *.dmg > KeeWeb-SHA512.txt

      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: true
          artifacts: "KeeWeb-*"

      - name: Publish release with notes
        uses: cyosp/publish-release-with-notes@2.0.0
        with:
          id: ${{ steps.release.outputs.id }}
          version: ${{ steps.tag.outputs.NAME }}
          notes: ${{ github.workspace }}/release-notes.md
